# 知识库相关配置


# 默认使用的知识库
DEFAULT_KNOWLEDGE_BASE: samples

# 默认的告警知识库
WARNING_KNOWLEDGE: warning

# 默认使用faiss向量数据库
DEFAULT_VS_TYPE: faiss

# 缓存向量库数量（针对FAISS）
CACHED_VS_NUM: 1

# 缓存临时向量库数量（针对FAISS），用于文件对话
CACHED_MEMO_VS_NUM: 2

# 缓存用户数（针对FAISS），用于记忆用户能力
CACHED_USER_VS_NUM: 2

# 知识库中单段文本长度(不适用MarkdownHeaderTextSplitter)
CHUNK_SIZE: 750

# 知识库中相邻文本重合长度(不适用MarkdownHeaderTextSplitter)
OVERLAP_SIZE: 150

# 知识库匹配向量数量
VECTOR_SEARCH_TOP_K: 3

# 知识库匹配相关度阈值，采用相似度，取值范围在-1-1之间，SCORE越大，相关度越高，取到-1相当于不筛选，建议设置在0.3左右
SCORE_THRESHOLD: 0.3

# 是否开启中文标题加强，以及标题增强的相关配置
ZH_TITLE_ENHANCE: false

# 每个知识库的初始化介绍
KB_INFO:
  samples: 关于本项目issue的解答

# TextSplitter配置项，如果你不明白其中的含义，就不要修改。
# source 如果选择tiktoken则使用openai的方法 "huggingface"
text_splitter_dict:
  ChineseRecursiveTextSplitter:
    source: ''
    tokenizer_name_or_path: ''
  MarkdownHeaderTextSplitter:
    headers_to_split_on:
      -   - '#'
          - head1
      -   - '##'
          - head2
      -   - '###'
          - head3
      -   - '####'
          - head4

# TEXT_SPLITTER 名称
TEXT_SPLITTER_NAME: ChineseRecursiveTextSplitter
